- helper/testing.go
See https://github.com/terraform-linters/tflint/pull/740
> helper: Compare Rule types with custom comparer

- plugin/plugin.go
- tflint/client.go
- tflint/client_test.go
See also https://github.com/hashicorp/hcl/issues/332
Currently, sending and receiving expression nodes via `gob` in the plugin system. However, this approach has two problems:
- Cannot support JSON syntax because `json.expression` is not exported
- Since it depends on the internal representation of the HCL package, changing this breaks plugin's compatibility.
After discussing this issue, I got the advice that it's best to use text representation for sending and receiving.
Following the advice, this PR changes that it sends and receives text instead of expression and it to be parsed as an expression by the plugin and host respectively.
Unfortunately, there is no expression-based JSON parsing API in HCL today. I'm opening a PR to add this function, but this pull request is pending until it …
> tflint: Sending expression nodes as a text representation

- go.sum
- tflint/client.go
- tflint/client_test.go
- tflint/interface.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/24
Similar to the expression, by transferring the body of the block in a text representation, we can pass the `hcl.Block` via RPC 🎉 
The missing piece is json's `Parse` function that allows you to specify the starting position. I've already confirmed that HCL can do that, but I'm worried about how to merge it into the core as it will be a backward-incompatible API change. https://github.com/wata727/hcl/commit/cf58d942a4c469a28142e5736bc73f448fa822a1
> tflint: Add WalkResourceBlocks API

- go.sum
- helper/runner.go
- helper/runner_test.go
- terraform/addrs.go
- terraform/configs.go
- terraform/doc.go
- tflint/client.go
- tflint/client_test.go
- tflint/decode.go
- tflint/interface.go
Fixes #36 
Add a `terraform.Resource` equivalent to `configs.Resource` so that more information can be used by the plugin.
> tflint: Support meta-arguments for terraform.Resource

- README.md
- plugin/plugin.go
This release breaks the API compatibility, so bump the protocol version.
> Bump protocol version

- terraform/configs.go
- tflint/client/client.go
- tflint/client/client_test.go
- tflint/client/decode.go
- tflint/client/rpc.go
- tflint/interface.go
- tflint/server/server.go
Closes #46.
This allows rulesets developed as plugins to add lint rules based on the
configuration of the state backend.
> Add `Runner.Backend()`

- go.mod
- go.sum
- helper/runner.go
- terraform/configs.go
- tflint/client/client.go
- tflint/client/decode.go
- tflint/client/rpc.go
- tflint/interface.go
- tflint/server/server.go
This allows rulesets to add lints that enforce rules on module calls
rather than only on resource declarations. I plan to use it, for
instance, to constrain the different forms of addresses used for
module sources.
Version constraints may be a bit different over the wire: the type exposed
by `go-version` can't necessarily be exactly reconstructed, as they've
been normalized under the hood. The original value is still accessible
through the usual `hcl.Body.PartialContent` or similar functions, if
needed.
In Terraform 0.12, I think the `Count` and `ForEach` struct members
will never actually be set, but the corresponding Terraform types have
them, so I've included them here. Maybe they'll Just Work once 0.13 is
out of beta and support is added to tflint.
> Implement `WalkModuleCalls`

- helper/runner.go
- terraform/addrs/module.go
- terraform/configs/config.go
- terraform/configs/module.go
- terraform/configs/named_values.go
- terraform/configs/provider.go
- terraform/experiments/experiment.go
- tflint/client/client.go
- tflint/client/decode.go
- tflint/client/decode_named_values.go
- tflint/client/decode_provider.go
- tflint/client/rpc.go
- tflint/interface.go
This PR introduces `Config` function to the Runner that returns an object equivalent to `github.com/hashicorp/terraform/configs.Config`.
Through this object, you will be able to access things like variables and outputs that were previously inaccessible.
> tflint: Add `Runner.Config()`

- helper/runner.go
- terraform/addrs/module.go
- terraform/configs/backend.go
- terraform/configs/config.go
- terraform/configs/module.go
- terraform/configs/module_call.go
- terraform/configs/named_values.go
- terraform/configs/provider.go
- terraform/configs/provisioner.go
- terraform/configs/resource.go
- terraform/configs/version_constraint.go
- terraform/experiments/experiment.go
This PR makes Terraform structures compatible with v0.13.2. There are no changes to the code.
> Make terraform configuration compatible with v0.13.2

- go.mod
- go.sum
- tflint/client/decode.go
Fixes https://github.com/terraform-linters/tflint-plugin-sdk/issues/32
HCL v2.7.0 has started to support parse JSON config/expression partially. We can take advantage of this to achieve partial server/client transfers of JSON configuration syntax.
> Add support for JSON configuration syntax

- plugin/client.go
- plugin/server.go
- tflint/config.go
- tflint/interface.go
- tflint/ruleset.go
This PR changes the `tflint.Ruleset` struct to the interface. This allows each plugin to serve a custom ruleset.
The previous behavior can be reproduced by using the `tflint.BuiltinRuleSet`. If you do not need plugin-specific processing, please use `tflint.BuiltinRuleSet` directly.
Custom rulesets can be used by declared a RuleSet with a `tflint.BuiltinRuleSet` embedded in the plugin and serving it. By overwriting the following method, you can insert the process specific to the plugin.
- `ApplyConfig`
- The argument `tflint.Config` contains the `hcl.Body` defined in the "plugin" block. You can handle plugin-specific configurations by decoding this with a custom ruleset.
- `Check`
- You can generate custom configurations built with `ApplyConfig`, custom runners that wrap provider API …
> Allow serving custom RuleSet by plugins

- helper/runner.go
- helper/testing.go
This PR extends the helper runner for testing. The following features are added:
- `cty.Value` is converted internally. This makes it possible to handle tuples and sets
- Decode `hcl.File` at initialization
- Support input variables in `EvaluateExpr`
> helper: Update helper runner

- helper/runner.go
- tflint/client/client.go
- tflint/client/decode_provider.go
- tflint/client/rpc.go
- tflint/interface.go
To cut out deep checking of AWS rules into a plugin, this PR extends runner API, adds `RootProvider` and `EvalExprOnRootCtx`.
In the ruleset plugin, an RPC server is assigned to each runner (module). If the target of the inspection is the root module, the provider configuration can be accessed, but the child module cannot access the provider configuration defined in the root.
To solve this problem, make use of the extended API to always have access to the root configuration.
See also https://github.com/terraform-linters/tflint/pull/986
> tflint: Extend runner API for accessing the root provider configuration

- helper/runner.go
- helper/testing.go
- tflint/client/client.go
- tflint/client/rpc.go
- tflint/interface.go
This PR adds an API for fetching rule config from plugins.
Add the `RuleConfig` method to the plugin server and return the encoded rule's configuration. The `DecodeRuleConfig` method added to the `Runner` decodes the acquired configuration into HCL and decodes it into a structure.
> tflint: Add support for fetching rule config

- helper/runner.go
- helper/runner_test.go
- tflint/client/client.go
- tflint/client/client_test.go
- tflint/client/rpc.go
- tflint/interface.go
This PR extends the `EvaluateExpr` API to add the `wantType` argument. This allows the mapping of the evaluated value to a complex object.
If you don't need to pass the type explicitly, you can pass `nil` to keep it working as before.
> tflint: Add wantType argument to EvaluateExpr

- helper/runner.go
- tflint/client/client.go
- tflint/client/rpc.go
- tflint/interface.go
This PR adds `IsNullExpr` runner API for checking whether the expression is null or not.
This is the last piece needed to cut out AWS rules into a plugin.
> tflint: Add `IsNullExpr` API

- helper/runner.go
- tflint/client/client.go
- tflint/client/client_test.go
- tflint/client/rpc.go
- tflint/interface.go
This PR changes the way the plugin client gets bytes in HCL files.
Previously, the client read files from the disk directly. It works because the plugin process is always in the same directory as the host process. However, language server chdirs to the directory of the opened file and does not work properly in that case.
To solve this problem, the host process should read the bytes of the file, and the plugin will fetch it via RPC. This PR adds the `File` API and replace the existing` ioutil.ReadFile` with this API calls.
> Avoid to read file directly from plugin side

- terraform/addrs/module.go
- terraform/configs/backend.go
- terraform/configs/config.go
- terraform/configs/module.go
- terraform/configs/module_call.go
- terraform/configs/named_values.go
- terraform/configs/provider.go
- terraform/configs/provisioner.go
- terraform/configs/resource.go
- terraform/configs/version_constraint.go
- terraform/experiments/experiment.go
- tflint/client/decode_named_values.go
`Sensitive` and `SensitiveSet` was added to `configs.Variable` in Terraform v0.14. See https://github.com/hashicorp/terraform/pull/26183 https://github.com/hashicorp/terraform/pull/26443
> Make terraform configuration compatible with v0.14

- tflint/client/decode.go
See https://github.com/hashicorp/hcl/issues/441
Added a workaround for this bug.
> tflint: Add workaround for parsing heredoc expressions

- plugin/plugin.go
- tflint/client/decode_named_values.go
This is a follow-up PR for terraform-linters/tflint#1041
> Use msgpack to encoding to pass cty.Value in variable default

- tflint/client/decode_named_values.go
After addressing cty.Value transfer in #96 cty.Type also needed to be encoded, because gob do not support cty.DynamicPseudoType (whish is "any" in terraform syntax)
msgpack cannot encode cty.Type, but it can be encoded by json
Related changes to tflint are in terraform-linters/tflint#1041
> Use json for transfering cty.Type

- helper/runner.go
I'm working on a plugin which checks that resource names include
`${terraform.workspace}` (if it's set) -
https://github.com/richardTowers/tflint-ruleset-workspaces/
Currently it's not possible to test this functionality, because (unlike
tflint) tflint-plugin-sdk doesn't support the `${terraform.workspace}`
expression.
Fixing https://github.com/terraform-linters/tflint-plugin-sdk/issues/64
would be nicer, but as this is quite self contained I think it's okay to
add this feature to the TestRunner.
> Allow use of ${terraform.workspace} in tests

- tflint/client/decode.go
Relates terraform-linters/tflint#1029
Workaround added in #93 should also be added to parseConfig function
> Fix heredoc parsing in parseConfig

- tflint/ruleset.go
See also https://github.com/terraform-linters/tflint/pull/1043 https://github.com/terraform-linters/tflint/issues/1054
This PR adds the `EnabledRules` field to the` BuiltinRuleSet` so that it doesn't change the `Rules` field.
The `Rules` field always returns all rules provided by the ruleset, regardless of the configuration, so that the validation behavior doesn't change with or without the configuration applied.
> tflint: Make sure RuleNames always return all rules

- helper/runner.go
This is just used in the test runner, but we may as well be consistent
with the variable used in terraform and mainline tflint.
As suggested here: https://github.com/terraform-linters/tflint-plugin-sdk/pull/99#discussion_r563246414
As per the docs here: https://www.terraform.io/docs/cli/config/environment-variables.html#tf_workspace
(This is a super minor change. No urgency at all, just cleaning stuff up.)
> Use a consistent env var for TF_WORKSPACE

- tflint/client/client.go
See also https://github.com/terraform-linters/tflint-ruleset-aws/issues/48
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/83
In #83, EvalExpr can now accept a type. If the type is passed, the object that reflects the evaluated result does not need to be sent to the server.
For instance, cty-based evaluation requires passing a complex object, which can cause gob encoding errors. This PR prevents the object from being included in the request when a detailed type is passed.
> Pass only type to EvalExpr when passed detailed types

- helper/runner.go
- helper/runner_test.go
- helper/testing.go
- tflint/client/client.go
- tflint/client/rpc.go
- tflint/interface.go
- tflint/server/server.go
Enables the use of Files() method on tflint-plugin-sdk.
This PR also brings a small refactoring as the Files property would conflict with the new Files() method.
> Implement Files() method

- tflint/config.go
Fixes https://github.com/terraform-linters/tflint-plugin-sdk/issues/127
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/93
If a `plugin` block ends with a heredoc (e.g. `signing_key`), the heredoc will not contain a trailing newline when the plugin side process parses the configuration. This does not meet the grammar of the heredoc and results in an "Unterminated template string" error.
As with https://github.com/terraform-linters/tflint-plugin-sdk/pull/93, `Unmarshal` always adds a trailing newline when parsing the body. However, this is a pretty bad workaround. The biggest difference from https://github.com/terraform-linters/tflint-plugin-sdk/pull/93 is that the added newline is meaningful. When parsing an expression, newlines are always ignored and do not affect …
> tflint: Add workaround when parsing a config that has a trailing heredoc

- helper/runner.go
- helper/runner_test.go
It panics when you use `helper.Runner` with variables. This PR fixes this issue.
> helper: Fix panic when helper runner uses variables

- helper/runner.go
- helper/runner_test.go
When calling `helper.TestRunner`, `variable` blocks with any attribute other than `default` will trigger a parsing error. The runner needs to read the `default` and other attributes should silently pass through. Currently, they cause a panic.
With the modified test:
```
--- FAIL: Test_EvaluateExpr (0.00s)
--- FAIL: Test_EvaluateExpr/string_interpolation (0.00s)
panic: Failed to initialize runner: main.tf:3,2-6: Unsupported argument; An argument named "type" is not expected here. [recovered]
panic: Failed to initialize runner: main.tf:3,2-6: Unsupported argument; An argument named "type" is not expected here.
goroutine 6 [running]:
testing.tRunner.func1.2({0x12fb300, 0xc000049e20})
/usr/local/Cellar/go/1.18/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1() …
```
> Skip un-used `variable` block attributes

- plugin/host2plugin/host2plugin_test.go
- plugin/plugin2host/plugin2host_test.go
- plugin/plugin2host/server.go
See also https://github.com/terraform-linters/tflint/pull/1365
This PR changes the value for encoding returned by `GetRuleConfigContent` from `*hcl.File` to `map[string][]bytes`. This change is a host-side change and has no impact on plugins.
> plugin2host: Return sources instead of *hcl.File in GetRuleConfigContent

- helper/runner.go
- plugin/plugin2host/client.go
- plugin/plugin2host/plugin2host_test.go
- tflint/interface.go
Fixes https://github.com/terraform-linters/tflint-plugin-sdk/issues/167
This PR adds `GetProviderContent` method to Runner. This is the same as `GetResourceContent` for providers, and is internally syntactic sugar for `GetModuleContent`.
> Add GetProviderContent helper

- helper/runner_test.go
- helper/testing.go
Currently, the `TestRunner` accepts only native HCL syntax files. This PR adds support for JSON syntax files.
If it contains files with filenames ending in `.json`, parse the files with `ParseJSON` instead of `ParseHCL`.
> helper: Add support for JSON syntax in TestRunner

- hclext/structure.go
- hclext/structure_test.go
- helper/runner.go
- helper/runner_test.go
- plugin/plugin2host/client.go
- plugin/plugin2host/plugin2host_test.go
- plugin/plugin2host/server.go
See also https://github.com/terraform-linters/tflint/pull/1481
Currently, The `DecodeRuleConfig` returns an error when the passed rule config is not found. However, this behavior is inconvenient when calling `DecodeRuleConfig` on rules with default config.
This PR allows calling `DecodeRuleConfig` without rule config. This change needs https://github.com/terraform-linters/tflint/pull/1481 change.
> Allow calling DecodeRuleConfig without rule config

- helper/runner.go
- helper/runner_test.go
- plugin/plugin2host/client.go
- plugin/plugin2host/plugin2host_test.go
- tflint/interface.go
- tflint/walker.go
This PR adds `WalkExpressions` function as a new runner API. This function is a wrapper that applies a callback function to all `hcl.Expression` retrieved using `GetFiles()`.
This function is useful for detecting all variable references contained within expressions, or forbidding certain resource references entirely. The argument can be a simple callback function, or any struct that satisfies the `ExprWalker` interface. If you pass a callback function, it will be invoked for every expression.
The internal implementation uses `hclsyntax.Walk`. So for example a callback will be called 3 times to `"${var.foo}-${var.bar}"` for itself, `var.foo` and `var.bar`. On the other hand, note that it behaves differently for JSON syntax. A callback is not called for `var.foo` and `var.bar`. Nor does it …
> tflint: Add WalkExpressions function

- tflint/ruleset.go
The `ApplyCommonConfig` had been used for the legacy plugin protocol. This function is unused in the gRPC plugin protocol.
> Remove unused ruleset function

- logger/logger.go
The log output includes the line number in an assembler, which is clearly wrong.
```
12:42:42 [WARN]  go-plugin@v1.4.5/client.go:355: plugin configured with a nil SecureConfig
12:42:42 [DEBUG] go-plugin@v1.4.5/client.go:355: starting plugin: path=/home/codespace/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-aws/0.16.1/tflint-ruleset-aws args=["/home/codespace/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-aws/0.16.1/tflint-ruleset-aws"]
12:42:42 [DEBUG] go-plugin@v1.4.5/client.go:355: plugin started: path=/home/codespace/.tflint.d/plugins/github.com/terraform-linters/tflint-ruleset-aws/0.16.1/tflint-ruleset-aws pid=17795
12:42:42 [DEBUG] go-plugin@v1.4.5/client.go:355: waiting for RPC address: path=/home/codespace/.tflint.d/plugins/github.com/terraform-linter …
```
> logger: Do not set location offset in go-plugin

- hclext/structure.go
This PR adds `Copy()` method to `hclext.BodyContent`, `hclext.Attribute`, and `hclext.Block`.
> Add Copy() to structures

- hclext/structure.go
- hclext/structure_test.go
This PR adds `WalkAttributes` method to `hclext.BodyContent`. This visits all attributes with the passed walker function.
It is useful for referencing all attributes in nested bodies.
> Add WalkAttribute to hclext.BodyContent

- tflint/interface.go
- tflint/ruleset.go
Fixes https://github.com/terraform-linters/tflint-plugin-sdk/issues/191
Add a `NewRunner` function in RuleSet so that built-in rulesets always use this function. This allows custom rulesets to inject a custom runner by simply redefining the `NewRunner`. No need to redefine `Check`.
> Allow a runner to be redefined within a ruleset

- plugin/fromproto/fromproto.go
- plugin/host2plugin/plugin.go
- plugin/plugin2host/client.go
- plugin/plugin2host/plugin2host_test.go
- tflint/errors.go
For historical reasons, errors from evaluating unknown or NULL values were handled on the server side rather than on the client side.
https://github.com/terraform-linters/tflint/blob/v0.45.0/plugin/server.go#L143-L167
But given that `EvaluateExpr` is an endpoint that returns a `cty.Value`, it's preferable to handle this error on the client side.
This PR adds unknown and NULL value handling in `plugin2host.GRPCClient.EvaluateExpr`. Below are compatibility notes:
- Before TFLint v0.46
- Both server-side and client-side are checked for errors. However, the added error is never returned as the error is always returned on the server side only.
- TFLint v0.46
- An error is returned on the client side only.
For all host versions, conversion of errors on Protocol Buffers may not be necessary once …
> plugin2host: Handle eval errors on the client side

- helper/runner.go
- plugin/plugin2host/client.go
- tflint/interface.go
Only pointers and callback functions are valid target values for `EvaluateExpr`. This PR clarifies the error messages if any other type is passed.
> Improve error messages for unexpected target types

- helper/runner.go
- plugin/plugin2host/client.go
- plugin/plugin2host/plugin2host_test.go
- tflint/interface.go
This PR changes `EvaluateExpr` to support the bool type as a target value. Previously the code below would error out as an unsupported target type:
```go
runner.EvaluateExpr(attr.Expr, func (enabled bool) error {
// Test values
}, nil)
```
At the same time `[]bool` and `map[string]bool` are also supported.
> Add support for the bool type as a target value

- plugin/host2plugin/host2plugin_test.go
- plugin/host2plugin/server.go
- tflint/interface.go
- tflint/ruleset.go
This PR removes `Check` method from `tflint.RuleSet` interface. Instead, add a `BuiltinImpl` method and move the inspection implementation for all enabled rules to `host2plugin.GRPCServer`.
This change means completely dropping the extensibility of the `Check` method from custom rulesets. This is a breaking change, but since the `Check` method is not originally intended to be overridden by custom rulesets, the impact is minimal.
> tflint: Remove Check method from tflint.RuleSet interface

- helper/runner.go
- helper/testing.go
In discussion of https://github.com/terraform-linters/tflint-ruleset-aws/pull/511, I noticed these two function are exported but labeled in their doc comment as "internal use only." I assumed this meant "we use this from other packages, but you shouldn't," which technically should be done in an `internal/` package to prevent external module callers.
But turns out that there isn't actually any usage outside the package:
https://github.com/search?q=org%3Aterraform-linters+NewLocalRunner&type=code
https://github.com/search?q=org%3Aterraform-linters+AddLocalFile&type=code
So to prevent any external use, I've un-exported these identifiers. Technically this is a breaking change but it shouldn't actually have any dependents.
> Un-export `NewLocalRunner` and `AddLocalFile`

- hclext/expression.go
See also https://github.com/terraform-linters/tflint-ruleset-aws/issues/522#issuecomment-1647992363
This PR adds support for expression unwrapping in `hclext.BoundExpr`. `BoundExpr` implements the `UnwrapExpression` method, allowing `hcl.UnwrapExpression` to return the original expression.
> hclext: Add support for expression unwrapping in hclext.BoundExpr

- helper/runner.go
- helper/runner_test.go
Follow up of https://github.com/terraform-linters/tflint-ruleset-terraform/pull/196
Until now, the test runner was not able to handle sensitive values, making it impossible to detect problems like https://github.com/terraform-linters/tflint-ruleset-terraform/pull/196 in unit tests.
This PR adds support for the `sensitive` attribute on variable blocks, making it easier to test marked values ​​like the following:
```hcl
variable "sensitive" {
default = "secret"
sensitive = true
}
```
> helper: Add support sensitive variables in TestRunner

- helper/runner.go
- helper/runner_test.go
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/358
See also https://github.com/terraform-linters/tflint-plugin-sdk/pull/337
This PR adds support for the `ephemeral` attribute on variable blocks, making it easier to test ephemeral values ​​like the following:
```hcl
variable "ephemeral" {
default = "secret"
ephemeral = true
}
```
> helper: Add support ephemeral variables in TestRunner

- helper/testing.go
Follow up of https://github.com/terraform-linters/tflint-ruleset-terraform/pull/216
Previously, `helper.AssertIssues` used in unit tests would even test whether the order of issues matched. However, the order in which the issues are emitted doesn't matter, as they will be sorted in the final output.
The order of iterations over a map is random, which makes test with `AssertIssues` flaky. Given this, it may not be a good idea to test the order in `AssertIssues`.
This PR adds `cmpopts.SortSlices`, which sorts issues, as a `cmp.Option` to `AssertIssues` and `AssertIssuesWithoutRange`, allowing you to ignore the order of issues.
> helper: Ignore issues order in helper.AssertIssues

- CHANGELOG.md
See https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
To take advantage of the auto-generated release notes, we will no longer update the CHANGELOG.md file included in the repository, but will add a link to the releases page.
> Stop updating CHANGELOG.md

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/lint.yml
See also https://www.wiz.io/blog/new-github-action-supply-chain-attack-reviewdog-action-setup
This PR makes GitHub Actions hash-pinned to reduce the risk of similar incidents.
Run `pinact run` with v1.4.0.
https://github.com/suzuki-shunsuke/pinact
> Pin GitHub Action versions
